package docker

import (
	"bytes"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"

	"gitlab.futo.org/stonefruit/stonefruit-server/installer/internal/config"
)

const ServerImageBase = "gitlab.futo.org:5050/stonefruit/stonefruit-server/server"
const ComposeFilename = "docker-compose.yml"
const EnvFilename = ".env"

// DefaultTrack is used when a fresh install doesn't pick one. "stable" follows
// tagged releases; "latest" follows main-branch pushes.
const DefaultTrack = "stable"

// Tracks enumerates valid release tracks.
var Tracks = []string{"stable", "latest"}

func ServerImage(track string) string {
	if track == "" {
		track = DefaultTrack
	}
	return ServerImageBase + ":" + track
}

func GenerateCompose(cfg config.Config) string {
	track := cfg.Track
	if track == "" {
		track = DefaultTrack
	}
	return fmt.Sprintf(`# Generated by stonefruit installer — do not edit manually
services:
  server:
    container_name: stonefruit
    image: %s
    ports:
      - "%d:3000"
    environment:
      DATABASE_URL: postgres://stonefruit:%s@postgres:5432/stonefruit
      PORT: "3000"
      BLOB_DIR: /data/blobs
      LOG_LEVEL: info
      AUTH_MODE: password
      STONEFRUIT_PASSWORD_HASH: ${STONEFRUIT_PASSWORD_HASH}
    volumes:
      - "%s:/data/blobs"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: stonefruit-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: stonefruit
      POSTGRES_PASSWORD: %s
      POSTGRES_DB: stonefruit
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stonefruit -d stonefruit"]
      interval: 5s
      timeout: 3s
      retries: 15

volumes:
  pg-data:
`, ServerImage(track), cfg.Port, cfg.PostgresPassword, cfg.DataPath, cfg.PostgresPassword)
}

func WriteCompose(workDir string, cfg config.Config) error {
	path := filepath.Join(workDir, ComposeFilename)
	return os.WriteFile(path, []byte(GenerateCompose(cfg)), 0o644)
}

// WriteEnvFile writes the sibling .env file that docker compose loads for
// ${...} substitution. Restricted to 0600 since the hash lives here.
func WriteEnvFile(workDir, passwordHash string) error {
	path := filepath.Join(workDir, EnvFilename)
	content := fmt.Sprintf("STONEFRUIT_PASSWORD_HASH=%s\n", passwordHash)
	return os.WriteFile(path, []byte(content), 0o600)
}

// ParseExistingEnv reads the hash from workDir/.env, or returns "" if the
// file or key is absent.
func ParseExistingEnv(workDir string) (string, error) {
	path := filepath.Join(workDir, EnvFilename)
	raw, err := os.ReadFile(path)
	if err != nil {
		if errors.Is(err, fs.ErrNotExist) {
			return "", nil
		}
		return "", err
	}
	for _, line := range strings.Split(string(raw), "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "STONEFRUIT_PASSWORD_HASH=") {
			return strings.TrimPrefix(line, "STONEFRUIT_PASSWORD_HASH="), nil
		}
	}
	return "", nil
}

// HashPassword shells out to the server image's `hash` subcommand so Go and
// TS always use the exact same scrypt format. Requires the image to be
// pullable; runs fresh in a throwaway container.
func HashPassword(image, password string) (string, error) {
	var stderr bytes.Buffer
	cmd := exec.Command("docker", "run", "--rm", image, "node", "dist/index.js", "hash", password)
	cmd.Stderr = &stderr
	out, err := cmd.Output()
	if err != nil {
		return "", fmt.Errorf("hash command failed: %v: %s", err, strings.TrimSpace(stderr.String()))
	}
	return strings.TrimSpace(string(out)), nil
}

var (
	rePort     = regexp.MustCompile(`(?m)^\s*-\s+"(\d+):3000"\s*$`)
	reDataPath = regexp.MustCompile(`(?m)^\s*-\s+"([^"]+):/data/blobs"\s*$`)
	rePassword = regexp.MustCompile(`(?m)^\s*POSTGRES_PASSWORD:\s+(\S+)\s*$`)
	reImage    = regexp.MustCompile(`(?m)^\s*image:\s+` + regexp.QuoteMeta(ServerImageBase) + `:(\S+)\s*$`)
)

// ParseExistingCompose reads workDir/docker-compose.yml and extracts the
// config. Returns (nil, nil) if the file does not exist.
func ParseExistingCompose(workDir string) (*config.Config, error) {
	path := filepath.Join(workDir, ComposeFilename)
	raw, err := os.ReadFile(path)
	if err != nil {
		if errors.Is(err, fs.ErrNotExist) {
			return nil, nil
		}
		return nil, err
	}
	cfg := &config.Config{}

	if m := rePort.FindSubmatch(raw); m != nil {
		p, err := strconv.Atoi(string(m[1]))
		if err != nil {
			return nil, fmt.Errorf("parse port in %s: %w", path, err)
		}
		cfg.Port = p
	} else {
		return nil, fmt.Errorf("could not find port in %s", path)
	}

	if m := reDataPath.FindSubmatch(raw); m != nil {
		cfg.DataPath = string(m[1])
	} else {
		return nil, fmt.Errorf("could not find data path in %s", path)
	}

	if m := rePassword.FindSubmatch(raw); m != nil {
		cfg.PostgresPassword = string(m[1])
	} else {
		return nil, fmt.Errorf("could not find postgres password in %s", path)
	}

	if m := reImage.FindSubmatch(raw); m != nil {
		cfg.Track = string(m[1])
	}

	return cfg, nil
}
