import { execFile, spawn } from 'node:child_process'
import { writeFile } from 'node:fs/promises'
import path from 'node:path'
import type { CliConfig } from './config.ts'

function exec(cmd: string, args: string[], cwd: string): Promise<string> {
  return new Promise((resolve, reject) => {
    execFile(cmd, args, { cwd }, (err, stdout, stderr) => {
      if (err) reject(new Error(`${cmd} ${args.join(' ')} failed: ${stderr || err.message}`))
      else resolve(stdout.trim())
    })
  })
}

function execPassthrough(cmd: string, args: string[], cwd: string): Promise<void> {
  return new Promise((resolve, reject) => {
    const child = spawn(cmd, args, { cwd, stdio: 'inherit' })
    child.on('close', (code: number) => {
      if (code === 0) resolve()
      else reject(new Error(`${cmd} exited with code ${code}`))
    })
  })
}

export async function checkDocker(): Promise<string> {
  try {
    return await exec('docker', ['version', '--format', '{{.Server.Version}}'], '.')
  } catch {
    throw new Error('Docker is not available. Install Docker and try again.')
  }
}

export async function composePull(workDir: string): Promise<void> {
  await execPassthrough('docker', ['compose', 'pull'], workDir)
}

export async function composeUp(workDir: string): Promise<void> {
  await execPassthrough('docker', ['compose', 'up', '-d', '--remove-orphans'], workDir)
}

export async function composeUpRecreate(workDir: string): Promise<void> {
  await execPassthrough('docker', ['compose', 'up', '-d', '--force-recreate', '--remove-orphans'], workDir)
}

export async function composeDown(workDir: string): Promise<void> {
  await execPassthrough('docker', ['compose', 'down'], workDir)
}

export async function getContainerImageId(name: string): Promise<string | null> {
  try {
    return await exec('docker', ['inspect', '--format', '{{.Image}}', name], '.')
  } catch {
    return null
  }
}

const SERVER_IMAGE = 'gitlab.futo.org:5050/stonefruit/stonefruit-e2ee-server-poc/server:latest'

function generateCompose(config: CliConfig): string {
  return `# Generated by stonefruit CLI — do not edit manually
services:
  server:
    container_name: stonefruit
    image: ${SERVER_IMAGE}
    ports:
      - "${config.port}:3000"
    environment:
      DATABASE_URL: postgres://stonefruit:${config.postgres_password}@postgres:5432/stonefruit
      PORT: "3000"
      BLOB_DIR: /data/blobs
      LOG_LEVEL: info
      AUTH_MODE: password
    volumes:
      - blob-data:/data/blobs
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: stonefruit-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: stonefruit
      POSTGRES_PASSWORD: ${config.postgres_password}
      POSTGRES_DB: stonefruit
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stonefruit -d stonefruit"]
      interval: 5s
      timeout: 3s
      retries: 15

volumes:
  pg-data:
  blob-data:
`
}

export async function writeCompose(workDir: string, config: CliConfig): Promise<void> {
  const content = generateCompose(config)
  await writeFile(path.join(workDir, 'docker-compose.yml'), content)
}
